org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=384M -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.configuration-cache=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

mod_version=0.0.1
maven_group=dev.mano
archives_base_name=mano

fabric_api_version=0.140.2+1.21.11
